### ISSUE TITLE
building list of files to parse fails on invalid symlink

### ISSUE THREAD

**Issue by gluedig** [apidoc/apidoc-core#16]
if there is invalid symlink in path used to find files to parse apidoc fails with error: 
> ENOENT, no such file or directory '.git/shallow'
debug: Error: ENOENT, no such file or directory '.git/shallow'
    at Object.fs.statSync (fs.js:693:18)
    at /home/gluedig/source/grinn/nubo/tools/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:81:10
    at Array.filter (native)
    at FindFiles.search (/home/gluedig/source/grinn/nubo/tools/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:77:23)
    at Parser.parseFiles (/home/gluedig/source/grinn/nubo/tools/apidoc/node_modules/apidoc-core/lib/parser.js:80:27)
    at Object.parse (/home/gluedig/source/grinn/nubo/tools/apidoc/node_modules/apidoc-core/lib/index.js:200:20)
    at Object.createDoc (/home/gluedig/source/grinn/nubo/tools/apidoc/lib/index.js:111:22)
    at Object.<anonymous> (/home/gluedig/source/grinn/nubo/tools/apidoc/bin/apidoc:107:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

adding a try/catch around line 81 in lib/utils/find_files.js helps

**Comment by rottmann** [comment]
Exclude the dir with `apidoc -e \\.git`
